### ISSUE TITLE
Filter cat expressions

### ISSUE THREAD

**Issue by TDiazT** [TDiazT/CoqR-Tester#1]
Cat expressions output just... anything, so it's hard to tell if an output corresponds to a cat case or to something 'unknown'.

The idea is to just filter these cases.

**Comment by Mbodin** [comment]
What if I actually add the cat expressions to ProveR? I added the possibility to do it in the state, and I think that it can be done (I just hope that the C code for cat in R is not too complex…). 
That way ProveR would also output the same thing, easing the comparison.

**Comment by TDiazT** [comment]
My only issue with this is that cat output could be anything and there's no way of telling it was a cat output or something else we didn't consider (`UNKNOWN`). Unless we would put a token before every cat expression in order to identify it or something in that line.

**Comment by Mbodin** [comment]
I can add such a token in the OCaml part. Would it help?
Another solution would be to run an R prelude at the beginning of each test involving 'cat' to make it print such a token before (and after?) the actual printing.
