### ISSUE TITLE
Add interpreters version on reports

### ISSUE THREAD

**Issue by TDiazT** [TDiazT/CoqR-Tester#16]

**Comment by Mbodin** [comment]
It would also be very nice to add the shell line to the report: this would help understanding what is being tested a lot.

**Comment by TDiazT** [comment]
You mean adding the cmd that was executed?

**Comment by Mbodin** [comment]
Exactly ☺

This can help understanding whether the test suite was from a particular file, a folder, etc. This also indicates where to look if looking for the JSON file.
