### ISSUE TITLE
Add comparable to make function match primitives

### ISSUE THREAD

**Issue by TDiazT** [TDiazT/CoqR-Tester#23]
builtin and special (from Coq) are translated into "Primitive"
The thing is, some actual primitives from R are printed as "function ... .Primitive", therefore considered functions...

Also, (closure) in Coq is translated to 'Function'.

Therefore, a function from R should be equivalent to:
builtin, special and closure

I'm not really sure, now that I think of it.. If it should be like this (could there be a case where it is mistaken?)

**Comment by Mbodin** [comment]
There are some frustating examples... For instance `.Primitive("if")`, which I think isn't printed as a function. :-/
I think that the best is to differenciate between basic values (strings, numbers, NA, NULL, etc.) and non-basic ones (closures, primitives, pairlists, environnments, etc.). For basic values, we should try to be as precise as possible. For non-basic values, I don't think that we need to be that precise: we can assume that the tests will project these to basic values at some point. So if we find « function » or « .Primitive » in the output, we can just say that it was a non-basic value. I think that this would simplify our work a lot. What do you think?

**Comment by TDiazT** [comment]
Mmh, so you say that for every non basic value just leave it as "non basic" and compare as such?

I agree though with what you said about these cases projecting eventually to basic values, so it would make sense

**Comment by Mbodin** [comment]
Exactly :-)
I think that almost all non-basic return values found in practise in tests are invisible, most probably due to an assigment. And as such, they are not very important to directly compare as the test will likely do something with it afterwards. If you find a counter-example, please tell me!
