### ISSUE TITLE
Add multiline interpretation

### ISSUE THREAD

**Issue by TDiazT** [TDiazT/CoqR-Tester#32]
Most of R tests (in src code) use multiline... So I should enable this

**Comment by TDiazT** [comment]
There's a couple of things:
 1. Identify each expression: This is basically parsing it... Not sure if I should wait for Martin (and use his parser written in Caml) or.. actually just base it off his implementation.
1. Eval each expression, with info from previous expressions:  
Maybe an option could be to identify assignments and then just add these to the following expressions:
    ```
    # Original
    a <- 1
    sum(a)

    # Adding
    a <- 1
    a <- 1; sum(a)
    ```

    The other option is to just eval the whole file but then it's harder to identify which expression generated which output and some files do not produce any output (eg. `any-all.R`).

**Comment by TDiazT** [comment]
Maybe it is possible to reuse rpy2 to handle it easier... But there is still the issue of running proveR with this, so basically it wouldn't be useful.

**Comment by TDiazT** [comment]
I noticed that I can actually use something from rscript itself:
```bash
$ rscript --help
Usage: /path/to/Rscript [--options] [-e expr [-e expr2 ...] | file] [args]

--options accepted are
  --help              Print usage and exit
  --version           Print version and exit
  --verbose           Print information on progress
  --default-packages=list
                      Where 'list' is a comma-separated set
                        of package names, or 'NULL'
or options to R, in addition to --slave --no-restore, such as
  --save              Do save workspace at the end of the session
  --no-environ        Don't read the site and user environment files
  --no-site-file      Don't read the site-wide Rprofile
  --no-init-file      Don't read the user R profile
  --restore           Do restore previously saved objects at startup
  --vanilla           Combine --no-save, --no-restore, --no-site-file
                        --no-init-file and --no-environ

'file' may contain spaces but not shell metacharacters
Expressions (one or more '-e <expr>') may be used *instead* of 'file'
See also  ?Rscript  from within R
```

I tried out the --save and --restore params and they work.

```bash
$ rscript --save --restore -e "(a <- function (x) x)"
function (x) 
x

$ rscript --save --restore -e "a(3)"
[1] 3

```

Or else, I could use multiple `-e` parameters, which also maintain objects through each expression ran.

Not sure if something like this can be done in proveR. I remember there is an option to save state in it, but I'm not sure if it could be used in such a manner...

**Comment by Mbodin** [comment]
I think that we can use the '-initial-state' parameter and 'save' command of ProveR for this. I don't see why it wouldn't work, but it might require some work to make it work as-is. I can also add an equivalent to the '-save' parameter if needed.

My fear is for tests that mess with the environment, like the test changing the meaning of parentheses. We probably want to offer a way to differentiate tests that should be executed as a normal R file and those that should be executed line by line. Or we can just split the latters into a lot of very small files... What do you think?

**Comment by TDiazT** [comment]
Yep, I'm not that sure about saving the state and later using it... I hadn't thought about those tests you mention 😋 . Also, If we want to know the context in which an expression fails we'd have to be displaying this state somehow (I mean.. I'm not sure that that's too hard xd.. but still).

What do you think about appending the definitions before each expression? As in the example above (similar to what we'd thought with those prebuilt functions defined in R)

**Comment by TDiazT** [comment]
Probably better to execute them like:
`rscript -e "e1" -e "e2" .... -e "e_n"`


Should add a "TOKEN" in between expressions, in order to relate outputs with expressions.

**Comment by TDiazT** [comment]
@Mbodin I'm having an issue running the code with multiline. 

Rscript (or R) can't run code with newlines, for example:
```
$ rscript -e "a <-\n1"
ARGUMENT '1' __ignored__

Error: unexpected end of input
Execution halted
```

Problem is that there are some expressions, such as:
```
# any-all.R
do_tests <- function(L)
{
    run <- function(f, input, na.rm = FALSE)
    {
        ...
    }

    do_check <- function(case, f)
    {
        fun <- deparse(substitute(f))
        ...
        narm <- paste(fun, ".na.rm", sep = "");
       ...
    }
    lab <- deparse(substitute(L))
    ...
}
```

Where, if I remove newlines before executing them, there is an error, due to those assignments... Basically, it can't parse `a <- {...} b <- {...}`.

What do you think?

**Comment by TDiazT** [comment]
Actually, there are other cases where it's a bit different but still causes problems:

```
# arith-true.R
rErr <- function(approx, true, eps = .Options$rErr.eps)
{
    if(is.null(eps)) { eps <- 1e-30; options(rErr.eps = eps) }
    ifelse(Mod(true) >= eps,
	   1 - approx / true, # relative error
	   true - approx)     # absolute error (e.g. when true=0)
}
```
There are commentaries in between code, which would comment everything if newlines are removed just like that.

**Comment by Mbodin** [comment]
This is very surprising… and unfortunate. :-/
I have made some tests, and I am surprised that the `\n` character doesn’t seem to be interpreted by bash as a new-line character.
``` bash
$ echo "a <- \n1"
a <- \n1
$ echo -e "a <- \n1"
a <- 
1
$ Rscript -e "a <- \n1"
Error: unexpected input in "a <- \"
Execution halted
$ Rscript -e "a <-
> 1"
ARGUMENT '1' __ignored__

Error: unexpected end of input
Execution halted
$ Rscript -e "a <- \
> 1"
$ # This last one seems to work on Bash. Can we try to call it that way in Python?
```
Maybe one solution would be to write on R input, like the following. Is there any profound reason why we should use Rscript instead of R?
``` bash
$ echo -e "a <- \n1\na" | R --quiet --no-save
> a <- 
+ 1
> a
[1] 1
> 
$ echo -e "a <- \n1\na" | R --quiet --no-save --slave
[1] 1
```

**Comment by TDiazT** [comment]
No, not really... rscript is just an interface above that one... I actually didn't think that would work 😆 (piping) .

I also checked [rpy2](https://rpy2.github.io/doc/latest/html/index.html) again - a Python library to run R - and managed to install without much trouble (before I tried an option which took 2h...). I also managed to run it from there.

Rpy2 runs R embedded in the python process but I don't know if it's easy to change the R version in use...

**Comment by TDiazT** [comment]
Daaaamn! Yep... doh, it was much easier that way hahaha 

So basically what I'm doing now is taking all the expressions in the file, adding some tokens in between and joining them all in one big expression which is then piped to R.

The only issue I see with this is that if at any point there is an error (in R), the execution will halt and not all expressions will be evaluated. When using the R tests it's fine... because... They made them so there are no errors but for any other case... I don't know

**Comment by Mbodin** [comment]
Great! Good thing that it works! ☺
I understand the issue. In some ways, this means that the “Potential fail” and “Potential pass” cases will disappear or be replaced by an “unknown” case, right? If so, I think that this is fine. We may have to think about how to understandably present such results, but I think that this is fine. ☺
