### ISSUE TITLE
Parse R files

### ISSUE THREAD

**Issue by TDiazT** [TDiazT/CoqR-Tester#34]
I think that in any case I will have to parse the R file to obtain the expressions in it... regardless of how I'll interpret them later, deal with env, etc.

**Comment by TDiazT** [comment]
This site has some useful info, https://tomassetti.me/parsing-in-python/

**Comment by TDiazT** [comment]
ANTLR actually has a defined grammar for R (https://github.com/antlr/grammars-v4/blob/master/r/R.g4) but I'm not sure if it's any good..

**Comment by Mbodin** [comment]
It looks very close to the R grammar. I have the feeling that they have simplified the new-line issue a lot, but it looks good to me. They have also removed the dead-code about the modulo, which is good :-)

**Comment by TDiazT** [comment]
Uhhh nice! :)

**Comment by TDiazT** [comment]
OK! I think the parsing is working, I get all the expressions from a file. I had to do some modifications to the grammars from their github though:

```
# R.g4
WS      :   [ \t\u000C]+ -> channel(HIDDEN) ;

# RFilter.g4

@members {
    self.curlies = 0
}

eat :   (NL {$NL.channel = Token.HIDDEN_CHANNEL})+ ;

    |   '{' eat? {self.curlies += 1} (elem|NL|';')* {self.curlies -= 1 } '}'
    |   'else'
        {
tok = self._input.LT(-2)
if self.curlies > 0 and tok.type == self.NL:
   tok.channel = Token.HIDDEN_CHANNEL
    }
```

The changes in the RFilter file are for the actions, which were set for Java and not Python. There is still a manual change I have to do with this in the `RFilter.py` file, line314:
```python
# Change this
(0 if (localctx._NL is None else localctx._NL.channel) = Token.HIDDEN_CHANNEL
# to
localctx._NL.channel = Token.HIDDEN_CHANNEL

```

The changes in the R.g4 file are in order to not entirely skip spaces, in order to retrieve them later when getting the full text.

**Comment by TDiazT** [comment]
One thing though, is that expressions in a sequence (with ';') are considered separate (which makes sense...) but I'm not sure how that will affect interpreting line by line
