### ISSUE TITLE
Change processing to be more specific

### ISSUE THREAD

**Issue by TDiazT** [TDiazT/CoqR-Tester#44]
Currently it matches a lot of things, so the idea is to reduce the amount to certain "basic" outputs. Also, the match should be from the beginning of the string and not just search around.

Problem with how it was is that sometimes it matches incorrectly, for example, `[1] "function"` was being processed as a `FUNCTION` instead of a string result.

So far, basic outputs are:

- Error
- Function (primitives too)
- NULL
- NA
- NaN
- Boolean
- String
- Number

**Comment by TDiazT** [comment]
Not sure if regex is the best option... It's a bit hard to maintain I think.

An example, for numeric output:
```python
r'^ *\[\d+\](?: (?:[+-]?(?:(?:[0-9]*[.])?[0-9]+(?:[eE][-+]?[0-9]+)*|Inf)|NA|NaN))+ *$'
```

This matches NA, NaN, mixes in between, integers, floating numbers, exponentials, infinity... But it's a bit complicated to understand...

**Comment by TDiazT** [comment]
For proveR, it's not matching some outputs due to the `>` at the beginning of the output!!

Example:
```
> Not implemented: [do_c]\nAn error lead to an undefined state. Continuing using the old one.\nAn error lead to an undefined result.\n> 
```

**Comment by Mbodin** [comment]
If this can help, I just added an option “-hide-prompt” to the interpreter to control this behaviour.

**Comment by TDiazT** [comment]
Are you sure it's included?
