### ISSUE TITLE
Change comparison between vector outputs to compare values

### ISSUE THREAD

**Issue by TDiazT** [TDiazT/CoqR-Tester#45]
Right now they are compared directly as strings but it should be compared based on the actual values:
```
-> [1] 1 2 3 [4] 5 6 7 
equals
-> [1] 1 2 3 5 6 7
```

**Comment by TDiazT** [comment]
Ok, so my main issue is how to do the comparisons of all kinds of outputs, in a way that's maintainable and extensible.

Right now the outputs are transformed into a case in an Enum, except for those outputs where there's more... "content", such as vectors. Those do not fall into a case, so it's more complicated to later retrieve and compare.

**Comment by Mbodin** [comment]
If you want to evaluate the extensibility of your approach, I suggest trying to parse pairlists. They are not difficult to parse, but this can still be a little tricky.
An example can for instance be `list (1, "2", list (3, "4"))`. I think that the output of Coq is very similar to R’s on this example. ☺
